Added "source" taxonomy for external stories
UCF/Today-Bootstrap pull request #29
Opened 2018-11-09 20:17 UTC by rjucf

2018-11-09 20:19 UTC, jmbarne3 approved these changes

2018-11-09 20:19 UTC, jmbarne3 commented on functions.php
> +	$source_name = wp_get_post_terms( $story_id, 'sources' )[0]->name;
If this doesn't return anything, it's potentially going to blow up for trying to access a property on a null objects, and/or an out of range index exception.

2018-11-09 20:19 UTC, jmbarne3 commented on custom-taxonomies.php
> +}
Some weird tabbing in the above block.

2018-11-09 20:54 UTC, cadie approved these changes

2018-11-09 21:02 UTC, cjg89 requested changes

2018-11-09 21:02 UTC, cjg89 commented on custom-taxonomies.php
> +		$general_name		= 'Post Tags',
Mixed tabs + spaces here.

2018-11-09 21:02 UTC, cjg89 commented on functions/api.php
> +			$search     = $request['search'];
Mixed tabs/spaces

2018-11-09 21:02 UTC, cjg89 commented on functions/api.php
> +			$retval['url']          = get_post_meta( $post->ID, 'externalstory_url', true );
Mixed tabs/spaces

2018-11-09 21:02 UTC, cjg89 commented on functions/api.php
> +            $retval['source_image'] = get_field( 'news_source_image', wp_get_post_terms( $post->ID, 'sources' )[0] )['url'];
line 117:  `wp_get_post_terms( $post->ID, 'sources' )[0]` will throw at least a notice if `wp_get_post_terms()` doesn't return at least one item, or if it returns `WP_Error`.

Trying to access `get_field(...)['url']` may also throw similar notices if a valid value isn't returned.

2018-11-09 21:02 UTC, cjg89 commented on functions/api.php
> +			$retval['source_name']  = wp_get_post_terms( $post->ID, 'sources' )[0]->name;
line 116: same issue Jim noted in functions.php.

2018-11-13 14:25 UTC, cjg89 approved these changes

2018-11-15 15:28 UTC, merged